<a href="https://colab.research.google.com/github/pav16an/PWSKILLS_FULLSTACK_DATA_SCIENCE_PRO/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. What is a Python library? Why ^o we use Python libraries?


A Python library is a collection of pre-written code that you can use in your own programs to perform common tasks. These libraries contain modules, which are files with reusable code that can be imported into your Python script.

We use Python libraries for several reasons:

**Efficiency:** Libraries save you time because you don't have to write code from scratch for common tasks. For example, instead of writing your own functions to handle complex mathematical operations, you can use the NumPy library.

**Reliability:** Libraries are often developed and tested by many people, so they are usually more reliable and have fewer bugs than code you might write yourself.

**Functionality:** Libraries can provide functionality that would be difficult or time-consuming to develop on your own. For example, the Pandas library provides powerful tools for data manipulation and analysis.

**Community Support:** Many libraries are open-source, meaning they have a community of developers who contribute to their development and offer support. This can be very helpful if you run into problems or have questions.

## 2. What is the difference between Numpy array and List?

A Python library is a collection of pre-written code that you can use in your own programs to perform common tasks. These libraries contain modules, which are files with reusable code that can be imported into your Python script.

We use Python libraries for several reasons:

Efficiency: Libraries save you time because you don't have to write code from scratch for common tasks. For example, instead of writing your own functions to handle complex mathematical operations, you can use the NumPy library.

Reliability: Libraries are often developed and tested by many people, so they are usually more reliable and have fewer bugs than code you might write yourself.

Functionality: Libraries can provide functionality that would be difficult or time-consuming to develop on your own. For example, the Pandas library provides powerful tools for data manipulation and analysis.

Community Support: Many libraries are open-source, meaning they have a community of developers who contribute to their development and offer support. This can be very helpful if you run into problems or have questions.

Overall, Python libraries make programming easier, faster, and more efficient by providing ready-to-use tools and functions.





2. What is the ^ifference between Numpy array an^ List? write as astudent
ChatGPT
The difference between a NumPy array and a list in Python is quite important, especially when working with data science or numerical computations. Here are the main differences:

Performance:

NumPy Array: NumPy arrays are more efficient for numerical operations and can handle large amounts of data faster. They use less memory and have better performance because they are implemented in C.
List: Lists are built-in Python data structures that are more flexible but slower for numerical operations because they are not optimized for such tasks.
Homogeneity:

NumPy Array: NumPy arrays require all elements to be of the same data type (e.g., all integers or all floats). This allows for more efficient storage and computation.
List: Lists can contain elements of different data types (e.g., integers, floats, strings) in the same list, which provides flexibility but can be less efficient for numerical computations.
Functionality:

NumPy Array: NumPy provides a wide range of mathematical and logical operations that can be performed on arrays. This includes element-wise operations, broadcasting, and linear algebra functions.
List: Lists are more general-purpose and don't have built-in support for advanced mathematical operations. You'd have to use loops or list comprehensions to perform similar tasks, which can be slower and more cumbersome.
Multidimensional Support:

NumPy Array: NumPy arrays can be multi-dimensional, making them very powerful for representing matrices, tensors, and higher-dimensional data structures.
List: While you can create lists of lists to represent multi-dimensional data, this approach is less efficient and lacks the advanced functionality provided by NumPy.
Memory Consumption:

NumPy Array: Due to their homogeneous nature and efficient implementation, NumPy arrays consume less memory compared to lists for large datasets.
List: Lists, being more flexible and able to hold heterogeneous data, generally consume more memory.

## 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
# shape of the array
import numpy as np

arr1=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f'Shape of the array is {arr1.shape}')

# size of the array
print(f'size of the array {arr1.size}')

# dimensions of the array
print(f'dimensions of the array {arr1.ndim}')


Shape of the array is (3, 4)
size of the array 12
dimensions of the array 2


## 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr2 = np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

print(f'first row of the array {arr2[0:1]} ')

first row of the array [[1 2 3 4]] 


## 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr2 =np.array( [[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

print(f'Third row and fourth column elements {arr2[2,3]} ')

Third row and fourth column elements 12 


## 6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f'Odd indexed elements are {arr3[0:3 , 1::2]}')

Odd indexed elements are [[ 2  4]
 [ 6  8]
 [10 12]]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [ ]:
arr4 = np.random.rand(3,3)
arr4

array([[0.74246246, 0.86388168, 0.69679191],
       [0.80332666, 0.93792353, 0.43157621],
       [0.85366848, 0.4080738 , 0.5410472 ]])

## 8. Describe the difference between np.random.rand and np.random.randn?

 The difference between np.random.rand and np.random.randn in NumPy lies in the The difference between np.random.rand and np.random.randn in NumPy lies in the distribution of the generated random numbers. Here’s a detailed comparison:

## np.random.rand
Purpose: Generates random numbers from a uniform distribution.
Range: The values are uniformly distributed between 0 and 1.
Usage: Commonly used when you need random numbers within a specific range.
Syntax:
python
Copy code
np.random.rand(d0, d1, ..., dn)
d0, d1, ..., dn: Dimensions of the returned array.
Example:


```
import numpy as np
# Generate a 3x3 matrix with random values between 0 and 1
uniform_random_matrix = np.random.rand(3, 3)
print(uniform_random_matrix)
```
Output:

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

##np.random.randn

Purpose: Generates random numbers from a standard normal distribution (Gaussian distribution).
Range: The values follow a normal distribution with a mean of 0 and a standard deviation of 1.
Usage: Used when you need random numbers that follow a normal distribution, often used in statistics, machine learning, and data analysis.

np.random.randn(d0, d1, ..., dn)
d0, d1, ..., dn: Dimensions of the returned array.
Example:
```
import numpy as np
# Generate a 3x3 matrix with random values from a standard normal distribution
normal_random_matrix = np.random.randn(3, 3)
print(normal_random_matrix)
```
Output:

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
Key Differences:
Distribution:

np.random.rand: Generates numbers from a uniform distribution between 0 and 1.
np.random.randn: Generates numbers from a standard normal distribution with a mean of 0 and a standard deviation of 1.
Usage:

Use np.random.rand when you need uniformly distributed random numbers within the range [0, 1].
Use np.random.randn when you need random numbers that follow a normal distribution, which is useful in various statistical applications and for initializing weights in neural networks.

## 9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr5=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
np.expand_dims(arr5,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

## 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
arr6=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr6.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
1. index wise multiplication
2. matrix multiplication
3. add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A


In [ ]:
# index wise multiplication
A = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
c=B.T

print(f'index wise multiplication {A*B}')
print(f'matrix wise multiplication {A@c}')
print(f'add both the matrics {A+B}')
print(f'Subtract matric B from A {A-B}')
print(f'DIvide Matrix {B/A}')

index wise multiplication [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
matrix wise multiplication [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
add both the matrics [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtract matric B from A [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
DIvide Matrix [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 12.  Which function in Numpy can be used to swap the byte order of an array?

In NumPy, the function used to swap the byte order of an array is numpy.ndarray.byteswap. This function allows you to swap the bytes of the array elements, which can be useful when dealing with data that has different endianness.



In [ ]:
import numpy as np

# Create an array with a specific byte order
arr = np.array([1, 256, 65536], dtype=np.int32)
print("Original array:")
print(arr)
print("Original array byte order:", arr.dtype.byteorder)

# Swap the byte order
swapped_arr = arr.byteswap().newbyteorder()
print("\nArray after byte swap:")
print(swapped_arr)
print("Swapped array byte order:", swapped_arr.dtype.byteorder)



Original array:
[    1   256 65536]
Original array byte order: =

Array after byte swap:
[    1   256 65536]
Swapped array byte order: >


## 13.  What is the significance of the np.linalg.inv function?


The np.linalg.inv function in NumPy is used to compute the inverse of a given square matrix. The inverse of a matrix
𝐴
A is a matrix
𝐴
−
1
A
−1
  such that when
𝐴
A is multiplied by
𝐴
−
1
A
−1
 , the result is the identity matrix
𝐼
I. In mathematical terms,
𝐴
×
𝐴
−
1
=
𝐴
−
1
×
𝐴
=
𝐼
A×A
−1
 =A
−1
 ×A=I.

Significance of np.linalg.inv:
Solving Linear Systems: The inverse of a matrix is often used to solve systems of linear equations. If
𝐴
𝑥
=
𝑏
Ax=b, then
𝑥
=
𝐴
−
1
𝑏
x=A
−1
 b. The np.linalg.inv function provides a straightforward way to find
𝐴
−
1
A
−1
 .

Matrix Operations: Inverse matrices are used in various matrix operations, including transformations, rotations, and scaling in graphics and engineering.

Theoretical Applications: In linear algebra and advanced mathematics, the concept of an inverse matrix is fundamental for understanding matrix decompositions, eigenvalues, eigenvectors, and other theoretical constructs.

In [ ]:
import numpy as np

# Define a square matrix A
A = np.array([[1, 2], [3, 4]])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)

print("\nInverse of Matrix A (A_inv):")
print(A_inv)

# Verify that A * A_inv = I
identity_matrix = np.dot(A, A_inv)
print("\nProduct of A and A_inv (should be identity matrix):")
print(identity_matrix)


Matrix A:
[[1 2]
 [3 4]]

Inverse of Matrix A (A_inv):
[[-2.   1. ]
 [ 1.5 -0.5]]

Product of A and A_inv (should be identity matrix):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the specified shape.

Syntax
python
Copy code
np.reshape(array, newshape, order='C')
array: The input array to be reshaped.
newshape: The new shape for the array. This can be an int or a tuple of ints.
order: Determines the order in which elements are read from the input array and placed into the reshaped array. Can be:
'C' (default) for row-major (C-style) order,
'F' for column-major (Fortran-style) order,
'A' for 'F' if the array is Fortran contiguous, 'C' otherwise,
'K' for retaining the order of the input array as much as possible.
Example
Here's an example of how to use np.reshape:

python
Copy code
import numpy as np

# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 array
reshaped_array = np.reshape(original_array, (2, 3))

print("Original array:")
print(original_array)

print("\nReshaped array (2x3):")
print(reshaped_array)
Output:

lua
Copy code
Original array:
[1 2 3 4 5 6]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
Important Points
Total Size: The total number of elements in the original array must match the total number of elements in the new shape. For example, a 6-element array can be reshaped to (2, 3) because
2
×
3
=
6
2×3=6.

Automatic Dimension Inference: You can use -1 in one of the dimensions to automatically infer what the dimension should be based on the total size of the array. For example:

python
Copy code
reshaped_array = np.reshape(original_array, (3, -1))
# This will reshape the array to (3, 2)
Order: The order parameter allows control over how elements are read and placed into the reshaped array, which can be important for performance and memory layout considerations.

## The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the specified shape.

Syntax
python
Copy code
np.reshape(array, newshape, order='C')
array: The input array to be reshaped.
newshape: The new shape for the array. This can be an int or a tuple of ints.
order: Determines the order in which elements are read from the input array and placed into the reshaped array. Can be:
'C' (default) for row-major (C-style) order,
'F' for column-major (Fortran-style) order,
'A' for 'F' if the array is Fortran contiguous, 'C' otherwise,
'K' for retaining the order of the input array as much as possible.
Example
Here's an example of how to use np.reshape:

python
Copy code
import numpy as np

# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 array
reshaped_array = np.reshape(original_array, (2, 3))

print("Original array:")
print(original_array)

print("\nReshaped array (2x3):")
print(reshaped_array)
Output:

lua
Copy code
Original array:
[1 2 3 4 5 6]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
Important Points
Total Size: The total number of elements in the original array must match the total number of elements in the new shape. For example, a 6-element array can be reshaped to (2, 3) because
2
×
3
=
6
2×3=6.

Automatic Dimension Inference: You can use -1 in one of the dimensions to automatically infer what the dimension should be based on the total size of the array. For example:

python
Copy code
reshaped_array = np.reshape(original_array, (3, -1))
# This will reshape the array to (3, 2)
Order: The order parameter allows control over how elements are read and placed into the reshaped array, which can be important for performance and memory layout considerations.

## The np.reshape function in NumPy is used to change the shape of an array without changing its data. It returns a new array with the specified shape.

Syntax
python
Copy code
np.reshape(array, newshape, order='C')
array: The input array to be reshaped.
newshape: The new shape for the array. This can be an int or a tuple of ints.
order: Determines the order in which elements are read from the input array and placed into the reshaped array. Can be:
'C' (default) for row-major (C-style) order,
'F' for column-major (Fortran-style) order,
'A' for 'F' if the array is Fortran contiguous, 'C' otherwise,
'K' for retaining the order of the input array as much as possible.
Example
Here's an example of how to use np.reshape:

python
Copy code
import numpy as np

# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 array
reshaped_array = np.reshape(original_array, (2, 3))

print("Original array:")
print(original_array)

print("\nReshaped array (2x3):")
print(reshaped_array)
Output:

lua
Copy code
Original array:
[1 2 3 4 5 6]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
Important Points
Total Size: The total number of elements in the original array must match the total number of elements in the new shape. For example, a 6-element array can be reshaped to (2, 3) because
2
×
3
=
6
2×3=6.

Automatic Dimension Inference: You can use -1 in one of the dimensions to automatically infer what the dimension should be based on the total size of the array. For example:

python
Copy code
reshaped_array = np.reshape(original_array, (3, -1))
# This will reshape the array to (3, 2)
Order: The order parameter allows control over how elements are read and placed into the reshaped array, which can be important for performance and memory layout considerations.

## 15. What is broadcasting in Numpy?

Broadcasting in NumPy refers to the ability to perform element-wise operations on arrays of different shapes. This feature allows NumPy to treat smaller arrays during arithmetic operations as if they have the same shape as the larger array, making array operations more efficient and concise.

Rules for Broadcasting
Alignment of Dimensions: Starting from the trailing dimensions (rightmost), NumPy compares dimensions of the input arrays.

Dimension Matching:

If the dimensions are equal, they are compatible.
If one of the dimensions is 1, it can be stretched to match the other dimension.
If neither dimension is 1 and they are not equal, broadcasting cannot be performed.
Resulting Shape: The resulting array shape is determined by taking the maximum size along each dimension of the input arrays.

In [1]:
import numpy as np

# 2D array (3x3)
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 1D array (3,)
b = np.array([1, 0, 1])

# Broadcasting addition
result = a + b

print("2D array (a):")
print(a)

print("\n1D array (b):")
print(b)

print("\nBroadcasted result (a + b):")
print(result)


2D array (a):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1D array (b):
[1 0 1]

Broadcasted result (a + b):
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
